    
name: ‘CA Action WeChat Bot’

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: "30 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Run Wechat Bot Note'
      uses: fifsky/wechat-work-action@v0.0.1
      with:
        # wechat work robot webhook
        url:  https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=bc90bba5-f8d1-4dbf-be95-f26066f3e751
        # message type
        type: text # optional, default is text
        # message content
        at: all
        content: "各位小伙伴，下班前请记得关灯~"
